genre_counts = movies90s_df['genre'].value_counts()
genre_counts.plot(kind='bar', title='Number of Movies by Genre in 1990s')
plt.ylabel('Number of Movies')
plt.xlabel('Genre')
plt.show()

movies90s_df['duration'].plot(kind='hist', bins=20, title='Distribution of Movie Durations (1990s)')
plt.xlabel('Duration (minutes)')
plt.ylabel('Frequency')
plt.show()